# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

TwoStatePhyloLikelihood <- function(treeEdges, tipStates, branchLengths, lambda_01, lambda_10, rootDist) {
    .Call('indorigin_TwoStatePhyloLikelihood', PACKAGE = 'indorigin', treeEdges, tipStates, branchLengths, lambda_01, lambda_10, rootDist)
}

twoStateSufficientStatistics <- function(treeEdges, tipStates, branchLengths, lambda_01, lambda_10, rootDist) {
    .Call('indorigin_twoStateSufficientStatistics', PACKAGE = 'indorigin', treeEdges, tipStates, branchLengths, lambda_01, lambda_10, rootDist)
}

