\documentclass[12pt]{article}

\usepackage{amsmath}
\usepackage{comment}
\usepackage{amscd}
\usepackage[utf8]{inputenc}
\usepackage{fancyhdr}

\usepackage{calc}
\usepackage{natbib}
\usepackage[american]{babel}

\setlength{\paperheight}{11in}
\setlength{\paperwidth}{8.5in}
\addtolength{\voffset}{-1.0in}
\addtolength{\hoffset}{-1.0in}
\setlength{\topmargin}{1in}
\setlength{\oddsidemargin}{1in}
\setlength{\evensidemargin}{1in}
\setlength{\textwidth}{\paperwidth - 2in}
\setlength{\textheight}{\paperheight - 2in}
\setlength{\footskip}{36pt}
\setlength{\marginparsep}{0.5cm}
\setlength{\marginparwidth}{1.5cm}
\setlength{\headheight}{0pt}
\setlength{\headsep}{0pt}



\pagestyle{fancy}
\renewcommand{\headrulewidth}{0pt}
\lhead{}
\chead{}
\rhead{}
\lfoot{}
\cfoot{\thepage}
\rfoot{}

\SweaveOpts{keep.source=TRUE}

\begin{document}

<<echo=FALSE>>=
options(width=40, continue=" ")
@

\begin{center}
  {\LARGE An rbrothers tutorial}\\\ \\
  {Jan Irvahn and Vladimir N. Minin \\ 
    Department of Statistics, University of Washington Seattle, WA, 98195, USA
  }
\end{center}

This is a tutorial demonstrating the usage of the java program, DualBrothers, in R.  To get started, install the rbrothers R package from R-forge. 
\begin{verbatim}
> install.packages("rbrothers", repos="http://R-Forge.R-project.org")
\end{verbatim}
The rJava package and a couple of other packages will need to be installed.

Start R and load the rbrothers library.
<<one>>=
library(rbrothers)
@

Copy the KAL153.phy file from the rbrothers package to your current working directory.
<<two>>=
my.align = read.dna(file=system.file("extdata/KAL153/KAL153.phy", 
	  	   package="rbrothers"))
write.dna(my.align,"KAL153.phy")
@

Now you can run DualBrothers with a single command.
<<three>>=
db<-dualbrothers(123,"KAL153",format="interleaved",par_lambda=5,top_lambda=0.693)
@

If you already have the output files of a DualBrothers run you can read the information in directly.
<<four>>=
db<-readdb("KAL153")
@

Plots can be created with the following commands.

<<label=plotdb>>=
plot(db,threshold=.5)
@
<<label=plotdb2>>=
plottree.db(db,type="phylogram",threshold=.5)
@



\begin{figure}[!t]
  \centering
<<label=dbfigure1,fig=TRUE,echo=FALSE, width=6,height=7.0>>=
<<plotdb>>
@
\caption{The top plot shows site specific posterior probabilities for the two most probable phylogenetic tree topologies. The bottom plot shows the site specific posterior probability of a breakpoint.}
\label{KALplot}
\end{figure}  

\begin{figure}[!t]
  \centering
<<label=dbfigure2,fig=TRUE,echo=FALSE, width=6,height=7.0>>=
<<plotdb2>>
@
\caption{These are the two most probable phylogenetic tree topologies.}
\label{KALplot2}
\end{figure}  


The average number of breakpoints, the posterior probability of at least one breakpoint and DualBrothers parameters associated with the run can be easily accessed.
<<five>>=
summary(db)
@

You can calculate a 95\% Bayesian credible interval for the first breakpoint.
<<six>>=
breakpointCI(db,1000,3000)
@


%\includegraphics[width=70mm]{KAL153plot1.png}
%\includegraphics[width=70mm]{KAL153plot2.png}


\end{document}

